/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  /*
    docs: [
      {
        type: 'category',
        label: 'Projects',
        link: {type: 'generated-index'},
        items: [
          'projects/deltabot',
          'projects/copbot'
        ]
      }
    ],
  */
  rootSidebar: [{ type: 'autogenerated', dirName: '.' }],
  projectsSidebar: [{ type: 'autogenerated', dirName: 'projects' }],
  literatureSidebar: [{ type: 'autogenerated', dirName: 'literature' }],
  // You can create a sidebar manually
  /*
  tutorialSidebar: [
    'intro',
    'hello',
    {
      type: 'category',
      label: 'Tutorial',
      items: ['tutorial-basics/create-a-document'],
    },
  ],
   */
};

module.exports = sidebars;
